// Static data extracted from CargoWatch Supabase
// Used for portal demo — no live DB dependency

export type IncidentType = "theft" | "suspicious" | "tampering" | "attempted_break_in";
export type SeverityLevel = "critical" | "high" | "medium" | "low";
export type IncidentStatus = "verified" | "under_investigation" | "resolved" | "pending" | "active" | "investigating" | "closed";

export interface CWRegion {
  id: string;
  name: string;
  state: string;
  city: string;
  latitude: number;
  longitude: number;
  isPriority: boolean;
  priorityRank: number | null;
  incidentCount: number;
}

export interface CWIncident {
  id: string;
  incidentType: IncidentType;
  severityLevel: SeverityLevel;
  cargoType: string;
  status: IncidentStatus;
  region: string;
  specificLocation: string;
  latitude: number;
  longitude: number;
  title: string;
  description: string;
  incidentDate: string;
  incidentTime: string;
  hasPhotos: boolean;
  hasVideo: boolean;
  evidenceCount: number;
  estimatedLoss: number;
  viewCount: number;
  commentCount: number;
  shareCount: number;
  reporterName: string;
  reporterCompany: string;
  reporterContact: string;
  createdAt: string;
}

export interface CWResource {
  id: string;
  category: string;
  subcategory: string;
  title: string;
  description: string;
  url: string;
  companyUrl: string | null;
  badge: string;
}

export const REGIONS: CWRegion[] = [
  { id: "3cf8d9c3", name: "Los Angeles, CA, USA", state: "CA", city: "Los Angeles", latitude: 34.0522, longitude: -118.2436, isPriority: true, priorityRank: 1, incidentCount: 2 },
  { id: "edd18f9c", name: "Memphis, TN, USA", state: "TN", city: "Memphis", latitude: 35.1495, longitude: -90.0489, isPriority: true, priorityRank: 2, incidentCount: 3 },
  { id: "5b8093e2", name: "London, United Kingdom", state: "UK", city: "London", latitude: 51.5074, longitude: -0.1278, isPriority: true, priorityRank: 3, incidentCount: 1 },
  { id: "c70d0414", name: "Singapore", state: "SG", city: "Singapore", latitude: 1.3521, longitude: 103.8198, isPriority: true, priorityRank: 4, incidentCount: 0 },
  { id: "a9978440", name: "Antwerp, Belgium", state: "BE", city: "Antwerp", latitude: 51.2194, longitude: 4.4025, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "1de15722", name: "Athens, Greece", state: "GR", city: "Athens", latitude: 37.9838, longitude: 23.7275, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "fcadfc58", name: "Atlanta, GA, USA", state: "GA", city: "Atlanta", latitude: 33.7489, longitude: -84.3879, isPriority: false, priorityRank: null, incidentCount: 5 },
  { id: "9ed961b1", name: "Auckland, New Zealand", state: "NZ", city: "Auckland", latitude: -36.8485, longitude: 174.7633, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "58c316ba", name: "Bangkok, Thailand", state: "TH", city: "Bangkok", latitude: 13.7563, longitude: 100.5018, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "83f60764", name: "Barcelona, Spain", state: "ES", city: "Barcelona", latitude: 41.3851, longitude: 2.1734, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "5b0bbafc", name: "Bogotá, Colombia", state: "CO", city: "Bogotá", latitude: 4.711, longitude: -74.0721, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "1482331d", name: "Buenos Aires, Argentina", state: "AR", city: "Buenos Aires", latitude: -34.6037, longitude: -58.3816, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "7b9093af", name: "Cairo, Egypt", state: "EG", city: "Cairo", latitude: 30.0444, longitude: 31.2357, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "dad21442", name: "Chicago, IL, USA", state: "IL", city: "Chicago", latitude: 41.8781, longitude: -87.6298, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "7448f235", name: "Dallas, TX, USA", state: "TX", city: "Dallas", latitude: 32.7766, longitude: -96.7969, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "09d3ef4b", name: "Dubai, UAE", state: "AE", city: "Dubai", latitude: 25.2048, longitude: 55.2708, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "1abb0fa8", name: "Hamburg, Germany", state: "DE", city: "Hamburg", latitude: 53.5511, longitude: 9.9937, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "881b6262", name: "Hong Kong", state: "HK", city: "Hong Kong", latitude: 22.3193, longitude: 114.1694, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "340958a9", name: "Houston, TX, USA", state: "TX", city: "Houston", latitude: 29.7604, longitude: -95.3698, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "3fb1e673", name: "Istanbul, Turkey", state: "TR", city: "Istanbul", latitude: 41.0082, longitude: 28.9784, isPriority: false, priorityRank: null, incidentCount: 5 },
  { id: "28238513", name: "Jakarta, Indonesia", state: "ID", city: "Jakarta", latitude: -6.2088, longitude: 106.8456, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "9468549b", name: "Jeddah, Saudi Arabia", state: "SA", city: "Jeddah", latitude: 21.5433, longitude: 39.1728, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "91964db5", name: "Johannesburg, South Africa", state: "ZA", city: "Johannesburg", latitude: -26.2041, longitude: 28.0473, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "f9981615", name: "Kuala Lumpur, Malaysia", state: "MY", city: "Kuala Lumpur", latitude: 3.139, longitude: 101.6869, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "41c7993f", name: "Lagos, Nigeria", state: "NG", city: "Lagos", latitude: 6.5244, longitude: 3.3792, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "73d8c0be", name: "Lima, Peru", state: "PE", city: "Lima", latitude: -12.0464, longitude: -77.0428, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "9cc9776f", name: "Melbourne, Australia", state: "AU", city: "Melbourne", latitude: -37.8136, longitude: 144.9631, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "92cf7eb0", name: "Mexico City, Mexico", state: "MX", city: "Mexico City", latitude: 19.4326, longitude: -99.1332, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "dec631d4", name: "Miami, FL, USA", state: "FL", city: "Miami", latitude: 25.7616, longitude: -80.1917, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "3ed513f1", name: "Milan, Italy", state: "IT", city: "Milan", latitude: 45.4642, longitude: 9.19, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "0f2c74cf", name: "Monterrey, Mexico", state: "NL", city: "Monterrey", latitude: 25.6866, longitude: -100.3161, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "4581e480", name: "Montreal, QC, Canada", state: "QC", city: "Montreal", latitude: 45.5017, longitude: -73.5673, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "95381c89", name: "Mumbai, India", state: "IN", city: "Mumbai", latitude: 19.076, longitude: 72.8777, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "672e2258", name: "Nairobi, Kenya", state: "KE", city: "Nairobi", latitude: -1.2864, longitude: 36.8172, isPriority: false, priorityRank: null, incidentCount: 6 },
  { id: "d3b0487b", name: "Newark, NJ, USA", state: "NJ", city: "Newark", latitude: 40.7357, longitude: -74.1724, isPriority: false, priorityRank: null, incidentCount: 0 },
  { id: "6e9960c4", name: "Paris, France", state: "FR", city: "Paris", latitude: 48.8566, longitude: 2.3522, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "d893874d", name: "Prague, Czech Republic", state: "CZ", city: "Prague", latitude: 50.0755, longitude: 14.4378, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "7664944c", name: "Rotterdam, Netherlands", state: "NL", city: "Rotterdam", latitude: 51.9225, longitude: 4.4792, isPriority: false, priorityRank: null, incidentCount: 3 },
  { id: "7395adee", name: "Santiago, Chile", state: "CL", city: "Santiago", latitude: -33.4489, longitude: -70.6693, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "b1735d80", name: "São Paulo, Brazil", state: "BR", city: "São Paulo", latitude: -23.5505, longitude: -46.6333, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "61bcd844", name: "Seattle, WA, USA", state: "WA", city: "Seattle", latitude: 47.6062, longitude: -122.332, isPriority: false, priorityRank: null, incidentCount: 4 },
  { id: "77d25263", name: "Seoul, South Korea", state: "KR", city: "Seoul", latitude: 37.5665, longitude: 126.978, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "15d7d715", name: "Shanghai, China", state: "CN", city: "Shanghai", latitude: 31.2304, longitude: 121.4737, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "c1bb6128", name: "Sydney, Australia", state: "AU", city: "Sydney", latitude: -33.8688, longitude: 151.2093, isPriority: false, priorityRank: null, incidentCount: 6 },
  { id: "e5d83e48", name: "Tel Aviv, Israel", state: "IL", city: "Tel Aviv", latitude: 32.0853, longitude: 34.7818, isPriority: false, priorityRank: null, incidentCount: 0 },
  { id: "da75e4a0", name: "Tokyo, Japan", state: "JP", city: "Tokyo", latitude: 35.6762, longitude: 139.6503, isPriority: false, priorityRank: null, incidentCount: 1 },
  { id: "077f6ba7", name: "Toronto, ON, Canada", state: "ON", city: "Toronto", latitude: 43.6532, longitude: -79.3832, isPriority: false, priorityRank: null, incidentCount: 5 },
  { id: "cdc830fa", name: "Vancouver, BC, Canada", state: "BC", city: "Vancouver", latitude: 49.2827, longitude: -123.1207, isPriority: false, priorityRank: null, incidentCount: 2 },
  { id: "6bd76346", name: "Warsaw, Poland", state: "PL", city: "Warsaw", latitude: 52.2297, longitude: 21.0122, isPriority: false, priorityRank: null, incidentCount: 4 },
];

export const INCIDENTS: CWIncident[] = [
  {
    id: "98b181d2-f8de-4ea2-861c-63b9a5a3e5c0",
    incidentType: "suspicious",
    severityLevel: "medium",
    cargoType: "pharmaceuticals",
    status: "active",
    region: "Santiago, Chile",
    specificLocation: "Santiago Chile",
    latitude: -33.4489000,
    longitude: -70.6693000,
    title: "Trailer Theft",
    description: "asdkfjhgkasdjfhgkhjsfd",
    incidentDate: "2026-01-21 00:00:00+00",
    incidentTime: "None",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 0,
    viewCount: 0,
    commentCount: 0,
    shareCount: 0,
    reporterName: "Test User",
    reporterCompany: "CargoWatch Demo",
    reporterContact: "test@cargowatch.com",
    createdAt: "2026-01-13 22:27:20.804824+00",
  },
  {
    id: "5ea504d2-535d-4ff9-a433-8e33320aedf6",
    incidentType: "suspicious",
    severityLevel: "low",
    cargoType: "None",
    status: "resolved",
    region: "Jeddah, Saudi Arabia",
    specificLocation: "Warehouse District",
    latitude: 21.5497000,
    longitude: 39.1355000,
    title: "Drone Activity Over Cargo Area",
    description: "Drone observed flying over secure container yard for extended period. Appeared to be surveying cargo areas. Operator not located. Increased vigilance recommended.",
    incidentDate: "2025-12-12 05:26:58.718+00",
    incidentTime: "04:53",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 6,
    estimatedLoss: 0.00,
    viewCount: 603,
    commentCount: 24,
    shareCount: 20,
    reporterName: "Driver",
    reporterCompany: "Warehouse Security",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "02a1ba1b-6832-4a64-ba06-dbea43ddeb58",
    incidentType: "theft",
    severityLevel: "high",
    cargoType: "electronics",
    status: "resolved",
    region: "BogotÃ¡, Colombia",
    specificLocation: "Warehouse District",
    latitude: 4.6853000,
    longitude: -74.0495000,
    title: "Container Theft from Secured Yard",
    description: "Container removed from secured facility overnight. Gate locks cut. Contains high-value electronics. Estimated loss $159,255. Investigation ongoing.",
    incidentDate: "2025-12-22 00:26:58.718+00",
    incidentTime: "17:24",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 159255.00,
    viewCount: 514,
    commentCount: 37,
    shareCount: 36,
    reporterName: "Fleet Manager",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "63ad83f1-d4cf-4bf6-a155-21831b0dc6c7",
    incidentType: "suspicious",
    severityLevel: "medium",
    cargoType: "None",
    status: "closed",
    region: "Seoul, South Korea",
    specificLocation: "Port Container Terminal",
    latitude: 37.6036000,
    longitude: 126.9880000,
    title: "Suspicious Vehicle Circling Facility",
    description: "Unmarked vehicle observed circling distribution center multiple times. Occupants appeared to be surveying cargo movements. License plate captured and reported.",
    incidentDate: "2025-12-25 19:26:58.718+00",
    incidentTime: "16:42",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 92725.00,
    viewCount: 164,
    commentCount: 10,
    shareCount: 60,
    reporterName: "Fleet Manager",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "4c76726c-a28f-4756-a894-cf5610a2f2ae",
    incidentType: "attempted_break_in",
    severityLevel: "high",
    cargoType: "general",
    status: "investigating",
    region: "Barcelona, Spain",
    specificLocation: "Port Container Terminal",
    latitude: 41.4321000,
    longitude: 2.1947000,
    title: "Attempted Break-in at Staging Area",
    description: "Bolt cutters and pry tools found near trailer. Locks show tampering but held. Incident occurred during overnight hours. Security footage being reviewed.",
    incidentDate: "2025-12-07 10:26:58.718+00",
    incidentTime: "04:20",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 2,
    estimatedLoss: 551906.00,
    viewCount: 603,
    commentCount: 37,
    shareCount: 7,
    reporterName: "Driver",
    reporterCompany: "Warehouse Security",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "4a572aeb-0687-4c93-b017-17eb4c29579c",
    incidentType: "tampering",
    severityLevel: "medium",
    cargoType: "food",
    status: "active",
    region: "London, United Kingdom",
    specificLocation: "Distribution Center",
    latitude: 51.5115000,
    longitude: -0.1360000,
    title: "Container Seal Tampering Detected",
    description: "Seal found broken during inspection. food shipment may be compromised. Full inventory check required. Incident logged with authorities.",
    incidentDate: "2025-12-16 14:26:58.718+00",
    incidentTime: "02:34",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 17090.00,
    viewCount: 309,
    commentCount: 3,
    shareCount: 41,
    reporterName: "Driver",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "1802930e-4f41-4d75-a9ab-aa2399bdda68",
    incidentType: "suspicious",
    severityLevel: "high",
    cargoType: "None",
    status: "investigating",
    region: "Kuala Lumpur, Malaysia",
    specificLocation: "Warehouse District",
    latitude: 3.1569000,
    longitude: 101.6502000,
    title: "Suspicious Activity Near Facility",
    description: "Multiple individuals observed inspecting trailers near cargo facility. Security team alerted. Subjects fled when approached. Dark SUV description provided to authorities.",
    incidentDate: "2025-12-06 00:26:58.718+00",
    incidentTime: "01:39",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 2,
    estimatedLoss: 329756.00,
    viewCount: 538,
    commentCount: 22,
    shareCount: 76,
    reporterName: "Independent O/O",
    reporterCompany: "J.B. Hunt Transport",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "d351f65c-723b-4ac7-9e7c-d496f44c6937",
    incidentType: "theft",
    severityLevel: "critical",
    cargoType: "pharmaceuticals",
    status: "resolved",
    region: "Santiago, Chile",
    specificLocation: "Staging Facility",
    latitude: -33.4567000,
    longitude: -70.6508000,
    title: "High-Value Pharmaceutical Theft",
    description: "Pharmaceutical shipment stolen during during rest break. GPS jammer suspected. Contains controlled substances. Law enforcement notified.",
    incidentDate: "2025-12-14 07:26:58.718+00",
    incidentTime: "03:04",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 4,
    estimatedLoss: 1154206.00,
    viewCount: 801,
    commentCount: 34,
    shareCount: 12,
    reporterName: "Facility Security",
    reporterCompany: "J.B. Hunt Transport",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "517a93ab-b994-4487-becd-a285f276525a",
    incidentType: "theft",
    severityLevel: "critical",
    cargoType: "electronics",
    status: "active",
    region: "Sydney, Australia",
    specificLocation: "Highway Rest Area",
    latitude: -33.8195000,
    longitude: 151.2108000,
    title: "Cargo Theft - Electronics Load Stolen",
    description: "Full trailer of consumer electronics stolen from secured facility. Professional operation with security bypass. Estimated value $1,196,668. Local authorities investigating.",
    incidentDate: "2025-12-13 18:26:58.718+00",
    incidentTime: "01:17",
    hasPhotos: false,
    hasVideo: true,
    evidenceCount: 0,
    estimatedLoss: 1196668.00,
    viewCount: 729,
    commentCount: 17,
    shareCount: 12,
    reporterName: "Security Officer",
    reporterCompany: "Warehouse Security",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "bf46aeab-dd47-490a-82b1-04484620be35",
    incidentType: "attempted_break_in",
    severityLevel: "medium",
    cargoType: "general",
    status: "closed",
    region: "Atlanta, GA, USA",
    specificLocation: "Warehouse District",
    latitude: 33.7062000,
    longitude: -84.4334000,
    title: "Security Lock Tampering Detected",
    description: "Lock shows signs of attempted tampering during rest stop. No cargo missing. Tools left at scene. Driver reported suspicious individuals in area.",
    incidentDate: "2025-12-19 21:26:58.718+00",
    incidentTime: "07:59",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 5,
    estimatedLoss: 13911.00,
    viewCount: 341,
    commentCount: 17,
    shareCount: 30,
    reporterName: "Independent O/O",
    reporterCompany: "XPO Logistics",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "d282ddd7-5f9a-470f-a9e4-86d18af2cfc5",
    incidentType: "tampering",
    severityLevel: "high",
    cargoType: "pharmaceuticals",
    status: "closed",
    region: "Memphis, TN, USA",
    specificLocation: "Intermodal Yard",
    latitude: 35.1448000,
    longitude: -90.0833000,
    title: "GPS Signal Interference Detected",
    description: "Multiple carriers reporting GPS signal loss in concentrated area. Possible jamming device in operation. Law enforcement investigating. Exercise extreme caution.",
    incidentDate: "2025-12-16 17:26:58.718+00",
    incidentTime: "15:57",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 4,
    estimatedLoss: 293405.00,
    viewCount: 517,
    commentCount: 3,
    shareCount: 66,
    reporterName: "Fleet Manager",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "8bbe764d-eabb-4ace-af11-4f970abe869d",
    incidentType: "suspicious",
    severityLevel: "low",
    cargoType: "None",
    status: "resolved",
    region: "Jeddah, Saudi Arabia",
    specificLocation: "Truck Stop",
    latitude: 21.5630000,
    longitude: 39.1249000,
    title: "Drone Activity Over Cargo Area",
    description: "Drone observed flying over secure container yard for extended period. Appeared to be surveying cargo areas. Operator not located. Increased vigilance recommended.",
    incidentDate: "2025-12-01 19:26:58.718+00",
    incidentTime: "13:48",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 6,
    estimatedLoss: 0.00,
    viewCount: 644,
    commentCount: 38,
    shareCount: 55,
    reporterName: "Fleet Manager",
    reporterCompany: "J.B. Hunt Transport",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "e01f51f2-89f5-4f15-b472-477a545c9054",
    incidentType: "theft",
    severityLevel: "high",
    cargoType: "electronics",
    status: "closed",
    region: "Cairo, Egypt",
    specificLocation: "Border Crossing",
    latitude: 30.0308000,
    longitude: 31.2724000,
    title: "Container Theft from Secured Yard",
    description: "Container removed from secured facility overnight. Gate locks cut. Contains high-value electronics. Estimated loss $196,472. Investigation ongoing.",
    incidentDate: "2025-12-05 13:26:58.718+00",
    incidentTime: "01:53",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 3,
    estimatedLoss: 196472.00,
    viewCount: 660,
    commentCount: 31,
    shareCount: 68,
    reporterName: "Fleet Manager",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "39555b34-a216-4f28-bc42-91ee77360414",
    incidentType: "suspicious",
    severityLevel: "medium",
    cargoType: "None",
    status: "investigating",
    region: "Atlanta, GA, USA",
    specificLocation: "Intermodal Yard",
    latitude: 33.7911000,
    longitude: -84.4261000,
    title: "Suspicious Vehicle Circling Facility",
    description: "Unmarked vehicle observed circling distribution center multiple times. Occupants appeared to be surveying cargo movements. License plate captured and reported.",
    incidentDate: "2025-12-01 22:26:58.718+00",
    incidentTime: "14:05",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 71222.00,
    viewCount: 329,
    commentCount: 24,
    shareCount: 58,
    reporterName: "Driver",
    reporterCompany: "J.B. Hunt Transport",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "96439df9-a598-461c-a1a2-8636d68a7079",
    incidentType: "attempted_break_in",
    severityLevel: "high",
    cargoType: "general",
    status: "closed",
    region: "Vancouver, BC, Canada",
    specificLocation: "Border Crossing",
    latitude: 49.3115000,
    longitude: -123.0952000,
    title: "Attempted Break-in at Staging Area",
    description: "Bolt cutters and pry tools found near trailer. Locks show tampering but held. Incident occurred during overnight hours. Security footage being reviewed.",
    incidentDate: "2025-12-14 15:26:58.718+00",
    incidentTime: "04:26",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 5,
    estimatedLoss: 393789.00,
    viewCount: 350,
    commentCount: 6,
    shareCount: 66,
    reporterName: "Fleet Manager",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "bce207ab-b4a3-4063-abe9-133cc5678f88",
    incidentType: "tampering",
    severityLevel: "medium",
    cargoType: "food",
    status: "closed",
    region: "Milan, Italy",
    specificLocation: "Truck Stop",
    latitude: 45.5107000,
    longitude: 9.2015000,
    title: "Container Seal Tampering Detected",
    description: "Seal found broken during inspection. food shipment may be compromised. Full inventory check required. Incident logged with authorities.",
    incidentDate: "2025-12-03 02:26:58.718+00",
    incidentTime: "05:29",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 52296.00,
    viewCount: 95,
    commentCount: 12,
    shareCount: 39,
    reporterName: "Fleet Manager",
    reporterCompany: "J.B. Hunt Transport",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "8d11a18e-5886-4bb3-b509-4b69f5ff0786",
    incidentType: "suspicious",
    severityLevel: "high",
    cargoType: "None",
    status: "resolved",
    region: "Prague, Czech Republic",
    specificLocation: "Distribution Center",
    latitude: 50.0891000,
    longitude: 14.4260000,
    title: "Suspicious Activity Near Facility",
    description: "Multiple individuals observed photographing facility near cargo facility. Security team alerted. Subjects fled when approached. White van description provided to authorities.",
    incidentDate: "2025-12-09 18:26:58.718+00",
    incidentTime: "22:49",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 1,
    estimatedLoss: 513010.00,
    viewCount: 789,
    commentCount: 9,
    shareCount: 69,
    reporterName: "Facility Security",
    reporterCompany: "Warehouse Security",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "c4871a55-5f74-4e44-b76e-ad0cc9195101",
    incidentType: "theft",
    severityLevel: "critical",
    cargoType: "pharmaceuticals",
    status: "closed",
    region: "Seattle, WA, USA",
    specificLocation: "Intermodal Yard",
    latitude: 47.6089000,
    longitude: -122.3039000,
    title: "High-Value Pharmaceutical Theft",
    description: "Pharmaceutical shipment stolen during overnight. GPS jammer suspected. Contains controlled substances. Law enforcement notified.",
    incidentDate: "2025-12-23 18:26:58.718+00",
    incidentTime: "14:12",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 1700847.00,
    viewCount: 402,
    commentCount: 22,
    shareCount: 66,
    reporterName: "Facility Security",
    reporterCompany: "Warehouse Security",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "2afd0505-ef78-48eb-8504-74f570556fe5",
    incidentType: "attempted_break_in",
    severityLevel: "medium",
    cargoType: "general",
    status: "active",
    region: "Bangkok, Thailand",
    specificLocation: "Highway Rest Area",
    latitude: 13.7122000,
    longitude: 100.5080000,
    title: "Security Lock Tampering Detected",
    description: "Lock shows signs of attempted tampering during rest stop. No cargo missing. Tools left at scene. Driver reported suspicious individuals in area.",
    incidentDate: "2025-12-20 18:26:58.718+00",
    incidentTime: "04:30",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 2,
    estimatedLoss: 109975.00,
    viewCount: 787,
    commentCount: 3,
    shareCount: 55,
    reporterName: "Facility Security",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "b45715e6-1e36-4ca3-af64-1636265ee7c0",
    incidentType: "tampering",
    severityLevel: "high",
    cargoType: "pharmaceuticals",
    status: "resolved",
    region: "Toronto, ON, Canada",
    specificLocation: "Intermodal Yard",
    latitude: 43.6106000,
    longitude: -79.4291000,
    title: "GPS Signal Interference Detected",
    description: "Multiple carriers reporting GPS signal loss in concentrated area. Possible jamming device in operation. Law enforcement investigating. Exercise extreme caution.",
    incidentDate: "2025-12-11 04:26:58.718+00",
    incidentTime: "02:04",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 2,
    estimatedLoss: 272547.00,
    viewCount: 356,
    commentCount: 5,
    shareCount: 25,
    reporterName: "Driver",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "e711d1c2-3c7d-446b-b8d7-3a1abd5aef6a",
    incidentType: "suspicious",
    severityLevel: "low",
    cargoType: "None",
    status: "investigating",
    region: "Jeddah, Saudi Arabia",
    specificLocation: "Truck Stop",
    latitude: 21.5658000,
    longitude: 39.1552000,
    title: "Drone Activity Over Cargo Area",
    description: "Drone observed flying over secure container yard for extended period. Appeared to be surveying cargo areas. Operator not located. Increased vigilance recommended.",
    incidentDate: "2025-12-05 08:26:58.718+00",
    incidentTime: "07:00",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 1,
    estimatedLoss: 0.00,
    viewCount: 321,
    commentCount: 4,
    shareCount: 74,
    reporterName: "Fleet Manager",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "5168ea53-e195-4d77-a4e1-f79d07991dcf",
    incidentType: "theft",
    severityLevel: "high",
    cargoType: "electronics",
    status: "closed",
    region: "Barcelona, Spain",
    specificLocation: "Highway Rest Area",
    latitude: 41.4330000,
    longitude: 2.1579000,
    title: "Container Theft from Secured Yard",
    description: "Container removed from secured facility overnight. Gate locks cut. Contains high-value electronics. Estimated loss $455,152. Investigation ongoing.",
    incidentDate: "2025-12-11 17:26:58.718+00",
    incidentTime: "11:37",
    hasPhotos: true,
    hasVideo: false,
    evidenceCount: 4,
    estimatedLoss: 455152.00,
    viewCount: 683,
    commentCount: 16,
    shareCount: 19,
    reporterName: "Security Officer",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "0e3ee7d0-a779-4423-98db-00a20abce73e",
    incidentType: "attempted_break_in",
    severityLevel: "high",
    cargoType: "general",
    status: "closed",
    region: "Hong Kong",
    specificLocation: "Staging Facility",
    latitude: 22.3493000,
    longitude: 114.1417000,
    title: "Attempted Break-in at Distribution Center",
    description: "Bolt cutters and pry tools found near trailer. Locks show tampering but held. Incident occurred during overnight hours. Security footage being reviewed.",
    incidentDate: "2025-12-13 20:26:58.718+00",
    incidentTime: "01:43",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 234183.00,
    viewCount: 87,
    commentCount: 27,
    shareCount: 6,
    reporterName: "Facility Security",
    reporterCompany: "XPO Logistics",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "da3e8572-8487-49b1-8399-c861af00f20d",
    incidentType: "tampering",
    severityLevel: "medium",
    cargoType: "food",
    status: "active",
    region: "Athens, Greece",
    specificLocation: "Warehouse District",
    latitude: 38.0103000,
    longitude: 23.7424000,
    title: "Container Seal Tampering Detected",
    description: "Seal found broken during inspection. food shipment may be compromised. Full inventory check required. Incident logged with authorities.",
    incidentDate: "2025-11-30 23:26:58.718+00",
    incidentTime: "00:30",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 36677.00,
    viewCount: 716,
    commentCount: 33,
    shareCount: 65,
    reporterName: "Security Officer",
    reporterCompany: "XPO Logistics",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "426b615a-88eb-4545-8bcf-8cdc9804445e",
    incidentType: "suspicious",
    severityLevel: "high",
    cargoType: "None",
    status: "investigating",
    region: "Athens, Greece",
    specificLocation: "Border Crossing",
    latitude: 38.0071000,
    longitude: 23.7655000,
    title: "Suspicious Activity Near Facility",
    description: "Multiple individuals observed photographing facility near cargo facility. Security team alerted. Subjects fled when approached. Unmarked truck description provided to authorities.",
    incidentDate: "2025-12-11 16:26:58.718+00",
    incidentTime: "16:25",
    hasPhotos: true,
    hasVideo: true,
    evidenceCount: 4,
    estimatedLoss: 299341.00,
    viewCount: 470,
    commentCount: 8,
    shareCount: 34,
    reporterName: "Fleet Manager",
    reporterCompany: "Independent O/O",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "1c972a9c-f774-4b38-92a8-bc953e6f030f",
    incidentType: "attempted_break_in",
    severityLevel: "medium",
    cargoType: "general",
    status: "resolved",
    region: "Toronto, ON, Canada",
    specificLocation: "Border Crossing",
    latitude: 43.6468000,
    longitude: -79.3562000,
    title: "Security Lock Tampering Detected",
    description: "Lock shows signs of attempted tampering during rest stop. No cargo missing. Tools left at scene. Driver reported suspicious individuals in area.",
    incidentDate: "2025-12-06 09:26:58.718+00",
    incidentTime: "13:35",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 78455.00,
    viewCount: 229,
    commentCount: 32,
    shareCount: 16,
    reporterName: "Driver",
    reporterCompany: "XPO Logistics",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
  {
    id: "8793c017-f93f-40f9-bb10-f238875752f3",
    incidentType: "tampering",
    severityLevel: "high",
    cargoType: "pharmaceuticals",
    status: "closed",
    region: "Istanbul, Turkey",
    specificLocation: "Highway Rest Area",
    latitude: 41.0539000,
    longitude: 29.0088000,
    title: "GPS Signal Interference Detected",
    description: "Multiple carriers reporting GPS signal loss in concentrated area. Possible jamming device in operation. Law enforcement investigating. Exercise extreme caution.",
    incidentDate: "2025-12-29 13:26:58.718+00",
    incidentTime: "22:19",
    hasPhotos: false,
    hasVideo: false,
    evidenceCount: 0,
    estimatedLoss: 264837.00,
    viewCount: 227,
    commentCount: 21,
    shareCount: 13,
    reporterName: "Security Officer",
    reporterCompany: "Swift Transportation",
    reporterContact: "",
    createdAt: "2025-12-30 20:26:58.992542+00",
  },
];

export const RESOURCES: CWResource[] = [
  { id: "0273284e", category: "product", subcategory: "gps_tracking", title: "CargoSafe GPS Tracker", description: "Real-time GPS tracking with tamper alerts and geofencing. Battery life up to 30 days.", url: "https://example.com/cargosafe", companyUrl: null, badge: "Partner" },
  { id: "94cef03d", category: "product", subcategory: "physical_security", title: "SmartSeal Electronic Locks", description: "Bluetooth-enabled trailer locks with instant breach notifications to your phone.", url: "https://example.com/smartseal", companyUrl: null, badge: "Featured" },
  { id: "694c8349", category: "educational", subcategory: "guide", title: "Cargo Theft Prevention Guide", description: "Comprehensive 50-page guide covering best practices, risk assessment, and security protocols.", url: "https://example.com/guide", companyUrl: null, badge: "Guide" },
  { id: "e5e27ede", category: "partnership", subcategory: "industry", title: "CargoNet Partnership", description: "CargoWatch integrates with CargoNet's national cargo theft database for enhanced tracking.", url: "https://cargonet.com", companyUrl: "https://cargonet.com", badge: "Partner" },
  { id: "239fad33", category: "partnership", subcategory: "industry", title: "FBI Cargo Theft Program", description: "Direct reporting channel to FBI's Cargo Theft Program for high-value incidents.", url: "https://fbi.gov/investigate/violent-crime/cargo-theft", companyUrl: null, badge: "Partner" },
  { id: "7156d19b", category: "product", subcategory: "surveillance", title: "TrailerCam 360° Security System", description: "24/7 video surveillance with motion detection and cloud storage. Solar-powered option available.", url: "https://example.com/trailercam", companyUrl: null, badge: "Featured" },
];

export const STATS = {
  totalIncidents: 129,
  totalUsers: 450,
  totalRegions: 49,
  criticalAlerts: 15,
  last30Days: 42,
  activeRegions: 47,
};

export const SEVERITY_COLORS: Record<SeverityLevel, { bg: string; text: string; dot: string }> = {
  critical: { bg: "bg-red-500/10", text: "text-cw-severity-critical", dot: "bg-cw-severity-critical" },
  high: { bg: "bg-orange-500/10", text: "text-cw-severity-high", dot: "bg-cw-severity-high" },
  medium: { bg: "bg-yellow-500/10", text: "text-cw-severity-medium", dot: "bg-cw-severity-medium" },
  low: { bg: "bg-green-500/10", text: "text-cw-severity-low", dot: "bg-cw-severity-low" },
};

export const INCIDENT_TYPE_LABELS: Record<IncidentType, string> = {
  theft: "Cargo Theft",
  suspicious: "Suspicious Activity",
  tampering: "Tampering",
  attempted_break_in: "Attempted Break-in",
};

export const CARGO_TYPES = [
  "electronics", "pharmaceuticals", "automotive", "textiles",
  "food_beverage", "chemicals", "machinery", "consumer_goods",
] as const;
