/**
 * Fabricated sample data for the showcase page.
 * All names, companies, and scenarios are illustrative -- no real client data.
 */

import type {
  ProjectWithMeta,
  TaskWithMeta,
} from "~/components/projects/types";
import type { ContactRow } from "~/components/crm/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);

// ---------------------------------------------------------------------------
// Projects (for ProjectKanban demo)
// ---------------------------------------------------------------------------
export const SAMPLE_PROJECTS: ProjectWithMeta[] = [
  {
    id: 1,
    name: "Soil Health Monitoring Platform",
    description:
      "Real-time soil sensor dashboard with historical trend analysis and alert thresholds for regenerative farms.",
    status: "active",
    isArchived: false,
    clientId: 1,
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
    _count: { tasks: 12, doneTasks: 8 },
  },
  {
    id: 2,
    name: "Urban Forest Canopy Tracker",
    description:
      "Satellite imagery integration for monitoring urban tree coverage, canopy health, and growth over time.",
    status: "active",
    isArchived: false,
    clientId: 2,
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
    client: { id: 2, name: "Terra Nova Collective", slug: "terra-nova" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
    _count: { tasks: 8, doneTasks: 3 },
  },
  {
    id: 3,
    name: "Watershed Management Dashboard",
    description:
      "Interactive watershed boundary maps with water quality metrics, flow data, and compliance reporting.",
    status: "on-hold",
    isArchived: false,
    clientId: 3,
    accountManagerId: "mm-1",
    assignedDeveloperId: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
    client: { id: 3, name: "Living Systems Co", slug: "living-systems" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: null,
    _count: { tasks: 6, doneTasks: 2 },
  },
  {
    id: 4,
    name: "Community Land Trust Portal",
    description:
      "Member portal for land trust administration -- property records, stewardship agreements, and community voting.",
    status: "active",
    isArchived: false,
    clientId: 4,
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
    client: { id: 4, name: "Rooted Commons", slug: "rooted-commons" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
    _count: { tasks: 15, doneTasks: 10 },
  },
  {
    id: 5,
    name: "Carbon Credit Verification System",
    description:
      "Automated verification pipeline for carbon sequestration credits with third-party auditor integration.",
    status: "completed",
    isArchived: false,
    clientId: 5,
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    createdAt: daysAgo(180),
    updatedAt: daysAgo(15),
    client: { id: 5, name: "Verdant Exchange", slug: "verdant-exchange" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
    _count: { tasks: 20, doneTasks: 20 },
  },
  {
    id: 6,
    name: "Regenerative Farm Planner",
    description:
      "Crop rotation planning tool with soil amendment recommendations based on cover crop history.",
    status: "on-hold",
    isArchived: false,
    clientId: 6,
    accountManagerId: "mm-1",
    assignedDeveloperId: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(20),
    client: {
      id: 6,
      name: "Perennial Agriculture Network",
      slug: "perennial-ag",
    },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: null,
    _count: { tasks: 4, doneTasks: 0 },
  },
];

// ---------------------------------------------------------------------------
// Tasks (for TaskKanban demo -- tied to project 1)
// ---------------------------------------------------------------------------
export const SAMPLE_TASKS: TaskWithMeta[] = [
  {
    id: 1,
    title: "Design sensor API schema",
    description: "Define tRPC endpoints for soil probe readings",
    status: "done",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(30).toISOString(),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(30),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
  {
    id: 2,
    title: "Build soil moisture dashboard",
    description: "Real-time chart with historical trend line",
    status: "done",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(20).toISOString(),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(20),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
  {
    id: 3,
    title: "Integrate satellite imagery layer",
    description: "Mapbox layer for NDVI vegetation index overlay",
    status: "in-progress",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-7).toISOString(),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
  {
    id: 4,
    title: "Deploy probe firmware OTA system",
    description: "Over-the-air firmware updates for field sensors",
    status: "in-progress",
    priority: "medium",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-14).toISOString(),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
  {
    id: 5,
    title: "Alert threshold configuration UI",
    description: "Admin panel for setting per-sensor alert rules",
    status: "todo",
    priority: "medium",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-21).toISOString(),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
  {
    id: 6,
    title: "CSV export for lab reports",
    description: "Download soil readings as formatted CSV for lab submission",
    status: "todo",
    priority: "low",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    project: { id: 1, name: "Soil Health Monitoring Platform" },
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    owner: { id: "mm-1", name: "Matthew Miceli" },
    accountManager: { id: "mm-1", name: "Matthew Miceli" },
    assignedDeveloper: { id: "mm-1", name: "Matthew Miceli" },
  },
];

// ---------------------------------------------------------------------------
// Contacts (for ContactKanban CRM demo)
// ---------------------------------------------------------------------------
export const SAMPLE_CONTACTS: ContactRow[] = [
  // Leads
  {
    id: "c-1",
    email: "elena@bioregionlabs.com",
    name: "Elena Vasquez",
    phone: "+1-512-555-0101",
    company: "Bioregion Labs",
    status: "lead",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["regenerative", "land-tech"],
    notes: "Interested in soil monitoring platform",
    lastContactAt: daysAgo(2),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-2",
    email: "james@greeninfra.org",
    name: "James Okafor",
    phone: null,
    company: "Green Infrastructure Alliance",
    status: "lead",
    source: "referral",
    referredBy: null,
    referredByExternal: "Conference contact",
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["urban", "community"],
    notes: "Met at regenerative cities summit",
    lastContactAt: daysAgo(5),
    submissionSources: ["manual"],
    portalClient: null,
  },
  {
    id: "c-3",
    email: "maria@seedcoop.org",
    name: "Maria Chen",
    phone: "+1-503-555-0199",
    company: "Seed Cooperative",
    status: "lead",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["agriculture", "cooperative"],
    notes: "Needs member management portal",
    lastContactAt: daysAgo(1),
    submissionSources: ["website"],
    portalClient: null,
  },
  // Prospects
  {
    id: "c-4",
    email: "david@terranova.co",
    name: "David Morales",
    phone: "+1-737-555-0142",
    company: "Terra Nova Collective",
    status: "prospect",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["land-tech", "carbon"],
    notes: "Proposal sent for canopy tracker",
    lastContactAt: daysAgo(3),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-5",
    email: "sarah@rootedcommons.org",
    name: "Sarah Whitfield",
    phone: "+1-512-555-0188",
    company: "Rooted Commons",
    status: "prospect",
    source: "referral",
    referredBy: null,
    referredByExternal: "David Morales",
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["community", "land-trust"],
    notes: "Scoping land trust portal features",
    lastContactAt: daysAgo(4),
    submissionSources: ["manual"],
    portalClient: null,
  },
  {
    id: "c-6",
    email: "kai@perennialag.net",
    name: "Kai Nakamura",
    phone: null,
    company: "Perennial Agriculture Network",
    status: "prospect",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["agriculture", "regenerative"],
    notes: "Interested in farm planning tool",
    lastContactAt: daysAgo(7),
    submissionSources: ["website"],
    portalClient: null,
  },
  // Clients
  {
    id: "c-7",
    email: "ana@livingsystems.co",
    name: "Ana Rivera",
    phone: "+1-512-555-0155",
    company: "Living Systems Co",
    status: "client",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["water", "land-tech"],
    notes: "Active watershed dashboard project",
    lastContactAt: daysAgo(1),
    submissionSources: ["website"],
    portalClient: {
      id: 3,
      slug: "living-systems",
      name: "Living Systems Co",
      company: "Living Systems Co",
    },
  },
  {
    id: "c-8",
    email: "marcus@verdantex.com",
    name: "Marcus Thompson",
    phone: "+1-415-555-0177",
    company: "Verdant Exchange",
    status: "client",
    source: "referral",
    referredBy: null,
    referredByExternal: "Ana Rivera",
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["carbon", "verification"],
    notes: "Carbon credit system delivered",
    lastContactAt: daysAgo(10),
    submissionSources: ["manual"],
    portalClient: {
      id: 5,
      slug: "verdant-exchange",
      name: "Verdant Exchange",
      company: "Verdant Exchange",
    },
  },
  {
    id: "c-9",
    email: "priya@bioregionlabs.com",
    name: "Priya Sharma",
    phone: "+1-512-555-0133",
    company: "Bioregion Labs",
    status: "client",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["regenerative", "land-tech", "sensors"],
    notes: "Soil monitoring -- phase 2 starting",
    lastContactAt: daysAgo(2),
    submissionSources: ["website"],
    portalClient: {
      id: 1,
      slug: "bioregion-labs",
      name: "Bioregion Labs",
      company: "Bioregion Labs",
    },
  },
  // Inactive
  {
    id: "c-10",
    email: "tom@oldgrowth.org",
    name: "Tom Bradley",
    phone: null,
    company: "Old Growth Foundation",
    status: "inactive",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["forestry"],
    notes: "Budget constraints -- revisit Q3",
    lastContactAt: daysAgo(60),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-11",
    email: "lisa@ecocraft.io",
    name: "Lisa Park",
    phone: "+1-206-555-0166",
    company: "EcoCraft Studios",
    status: "inactive",
    source: "manual",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["design"],
    notes: "Went with in-house solution",
    lastContactAt: daysAgo(45),
    submissionSources: ["manual"],
    portalClient: null,
  },
  // Churned
  {
    id: "c-12",
    email: "ryan@clearwater.co",
    name: "Ryan Foster",
    phone: null,
    company: "Clearwater Analytics",
    status: "churned",
    source: "referral",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["analytics"],
    notes: "Scope mismatch -- too enterprise-focused",
    lastContactAt: daysAgo(90),
    submissionSources: ["manual"],
    portalClient: null,
  },
];
