/**
 * Fabricated sample data for the showcase page.
 * All names, companies, and scenarios are illustrative -- no real client data.
 */

import type {
  ProjectWithMeta,
  TaskWithMeta,
} from "~/components/projects/types";
import type { ContactRow } from "~/components/crm/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);

// ---------------------------------------------------------------------------
// Projects (for ProjectKanban demo)
// ---------------------------------------------------------------------------
export const SAMPLE_PROJECTS: ProjectWithMeta[] = [
  {
    id: 1,
    name: "Soil Health Monitoring Platform",
    description:
      "Real-time soil sensor dashboard with historical trend analysis and alert thresholds for regenerative farms.",
    status: "active",
    isArchived: false,
    clientId: 1,
    accountManagerId: "ar-3",
    assignedDeveloperId: "jl-2",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
    client: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
    accountManager: { id: "ar-3", name: "Anika Rao" },
    assignedDeveloper: { id: "jl-2", name: "Jordan Lee" },
    _count: { tasks: 6, doneTasks: 2 },
  },
  {
    id: 2,
    name: "Urban Forest Canopy Tracker",
    description:
      "Satellite imagery integration for monitoring urban tree coverage, canopy health, and growth over time.",
    status: "active",
    isArchived: false,
    clientId: 2,
    accountManagerId: "ar-3",
    assignedDeveloperId: "tc-4",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
    client: { id: 2, name: "Terra Nova Collective", slug: "terra-nova" },
    accountManager: { id: "ar-3", name: "Anika Rao" },
    assignedDeveloper: { id: "tc-4", name: "Tyler Chen" },
    _count: { tasks: 5, doneTasks: 2 },
  },
  {
    id: 3,
    name: "Watershed Management Dashboard",
    description:
      "Interactive watershed boundary maps with water quality metrics, flow data, and compliance reporting.",
    status: "on-hold",
    isArchived: false,
    clientId: 3,
    accountManagerId: "ar-3",
    assignedDeveloperId: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
    client: { id: 3, name: "Living Systems Co", slug: "living-systems" },
    accountManager: { id: "ar-3", name: "Anika Rao" },
    assignedDeveloper: null,
    _count: { tasks: 0, doneTasks: 0 },
  },
  {
    id: 4,
    name: "Community Land Trust Portal",
    description:
      "Member portal for land trust administration -- property records, stewardship agreements, and community voting.",
    status: "active",
    isArchived: false,
    clientId: 4,
    accountManagerId: "jl-2",
    assignedDeveloperId: "ar-3",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
    client: { id: 4, name: "Rooted Commons", slug: "rooted-commons" },
    accountManager: { id: "jl-2", name: "Jordan Lee" },
    assignedDeveloper: { id: "ar-3", name: "Anika Rao" },
    _count: { tasks: 4, doneTasks: 2 },
  },
  {
    id: 5,
    name: "Carbon Credit Verification System",
    description:
      "Automated verification pipeline for carbon sequestration credits with third-party auditor integration.",
    status: "completed",
    isArchived: false,
    clientId: 5,
    accountManagerId: "jl-2",
    assignedDeveloperId: "tc-4",
    createdAt: daysAgo(180),
    updatedAt: daysAgo(15),
    client: { id: 5, name: "Verdant Exchange", slug: "verdant-exchange" },
    accountManager: { id: "jl-2", name: "Jordan Lee" },
    assignedDeveloper: { id: "tc-4", name: "Tyler Chen" },
    _count: { tasks: 3, doneTasks: 3 },
  },
  {
    id: 6,
    name: "Regenerative Farm Planner",
    description:
      "Crop rotation planning tool with soil amendment recommendations based on cover crop history.",
    status: "on-hold",
    isArchived: false,
    clientId: 6,
    accountManagerId: "ar-3",
    assignedDeveloperId: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(20),
    client: {
      id: 6,
      name: "Perennial Agriculture Network",
      slug: "perennial-ag",
    },
    accountManager: { id: "ar-3", name: "Anika Rao" },
    assignedDeveloper: null,
    _count: { tasks: 0, doneTasks: 0 },
  },
];

// ---------------------------------------------------------------------------
// Tasks (for TaskKanban demo -- spread across projects with diverse team)
// ---------------------------------------------------------------------------
const team = {
  mm: { id: "mm-1", name: "Matthew Miceli" },
  jl: { id: "jl-2", name: "Jordan Lee" },
  ar: { id: "ar-3", name: "Anika Rao" },
  tc: { id: "tc-4", name: "Tyler Chen" },
};

const proj = {
  soil: { id: 1, name: "Soil Health Monitoring Platform" },
  canopy: { id: 2, name: "Urban Forest Canopy Tracker" },
  watershed: { id: 3, name: "Watershed Management Dashboard" },
  landTrust: { id: 4, name: "Community Land Trust Portal" },
  carbon: { id: 5, name: "Carbon Credit Verification System" },
};

const client = {
  bioregion: { id: 1, name: "Bioregion Labs", slug: "bioregion-labs" },
  terraNova: { id: 2, name: "Terra Nova Collective", slug: "terra-nova" },
  livingSys: { id: 3, name: "Living Systems Co", slug: "living-systems" },
  rooted: { id: 4, name: "Rooted Commons", slug: "rooted-commons" },
  verdant: { id: 5, name: "Verdant Exchange", slug: "verdant-exchange" },
};

export const SAMPLE_TASKS: TaskWithMeta[] = [
  // --- Project 1: Soil Health (active, 8/12 done) ---
  {
    id: 1,
    title: "Design sensor API schema",
    description: "Define tRPC endpoints for soil probe readings",
    status: "done",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(30).toISOString(),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(30),
    project: proj.soil,
    client: client.bioregion,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.mm,
  },
  {
    id: 2,
    title: "Build soil moisture dashboard",
    description: "Real-time chart with historical trend line",
    status: "done",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "jl-2",
    dueDate: daysAgo(20).toISOString(),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(20),
    project: proj.soil,
    client: client.bioregion,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.jl,
  },
  {
    id: 3,
    title: "Integrate satellite imagery layer",
    description: "Mapbox layer for NDVI vegetation index overlay",
    status: "in-progress",
    priority: "high",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-7).toISOString(),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
    project: proj.soil,
    client: client.bioregion,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.mm,
  },
  {
    id: 4,
    title: "Deploy probe firmware OTA system",
    description: "Over-the-air firmware updates for field sensors",
    status: "in-progress",
    priority: "medium",
    projectId: 1,
    clientId: 1,
    ownerId: "jl-2",
    accountManagerId: "mm-1",
    assignedDeveloperId: "jl-2",
    dueDate: daysAgo(-14).toISOString(),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    project: proj.soil,
    client: client.bioregion,
    owner: team.jl,
    accountManager: team.mm,
    assignedDeveloper: team.jl,
  },
  {
    id: 5,
    title: "Alert threshold configuration UI",
    description: "Admin panel for setting per-sensor alert rules",
    status: "todo",
    priority: "medium",
    projectId: 1,
    clientId: 1,
    ownerId: "ar-3",
    accountManagerId: "mm-1",
    assignedDeveloperId: "ar-3",
    dueDate: daysAgo(-21).toISOString(),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    project: proj.soil,
    client: client.bioregion,
    owner: team.ar,
    accountManager: team.mm,
    assignedDeveloper: team.ar,
  },
  {
    id: 6,
    title: "CSV export for lab reports",
    description: "Download soil readings as formatted CSV for lab submission",
    status: "todo",
    priority: "low",
    projectId: 1,
    clientId: 1,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "jl-2",
    dueDate: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    project: proj.soil,
    client: client.bioregion,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.jl,
  },

  // --- Project 2: Canopy Tracker (active, 3/8 done) ---
  {
    id: 7,
    title: "Set up Mapbox tile server",
    description:
      "Configure satellite imagery tile endpoints for canopy analysis",
    status: "done",
    priority: "high",
    projectId: 2,
    clientId: 2,
    ownerId: "mm-1",
    accountManagerId: "ar-3",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(15).toISOString(),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(15),
    project: proj.canopy,
    client: client.terraNova,
    owner: team.mm,
    accountManager: team.ar,
    assignedDeveloper: team.mm,
  },
  {
    id: 8,
    title: "Tree detection ML pipeline",
    description: "Train YOLO model on urban canopy aerial imagery",
    status: "done",
    priority: "high",
    projectId: 2,
    clientId: 2,
    ownerId: "tc-4",
    accountManagerId: "ar-3",
    assignedDeveloperId: "tc-4",
    dueDate: daysAgo(10).toISOString(),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
    project: proj.canopy,
    client: client.terraNova,
    owner: team.tc,
    accountManager: team.ar,
    assignedDeveloper: team.tc,
  },
  {
    id: 9,
    title: "Canopy health scoring algorithm",
    description: "NDVI-based health index with seasonal normalization",
    status: "in-progress",
    priority: "high",
    projectId: 2,
    clientId: 2,
    ownerId: "tc-4",
    accountManagerId: "ar-3",
    assignedDeveloperId: "tc-4",
    dueDate: daysAgo(-5).toISOString(),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
    project: proj.canopy,
    client: client.terraNova,
    owner: team.tc,
    accountManager: team.ar,
    assignedDeveloper: team.tc,
  },
  {
    id: 10,
    title: "Growth trend visualization",
    description:
      "Historical canopy coverage charts with year-over-year comparison",
    status: "in-progress",
    priority: "medium",
    projectId: 2,
    clientId: 2,
    ownerId: "mm-1",
    accountManagerId: "ar-3",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-10).toISOString(),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
    project: proj.canopy,
    client: client.terraNova,
    owner: team.mm,
    accountManager: team.ar,
    assignedDeveloper: team.mm,
  },
  {
    id: 11,
    title: "Public dashboard for city planners",
    description:
      "Read-only dashboard with shareable link for municipal partners",
    status: "todo",
    priority: "medium",
    projectId: 2,
    clientId: 2,
    ownerId: "ar-3",
    accountManagerId: "ar-3",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(-20).toISOString(),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    project: proj.canopy,
    client: client.terraNova,
    owner: team.ar,
    accountManager: team.ar,
    assignedDeveloper: team.mm,
  },

  // --- Project 4: Land Trust Portal (active, 10/15 done) ---
  {
    id: 12,
    title: "Member authentication flow",
    description: "Supabase auth with magic link for land trust members",
    status: "done",
    priority: "high",
    projectId: 4,
    clientId: 4,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(60).toISOString(),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(60),
    project: proj.landTrust,
    client: client.rooted,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.mm,
  },
  {
    id: 13,
    title: "Property records CRUD",
    description:
      "Create, edit, and archive parcel records with document uploads",
    status: "done",
    priority: "high",
    projectId: 4,
    clientId: 4,
    ownerId: "jl-2",
    accountManagerId: "mm-1",
    assignedDeveloperId: "jl-2",
    dueDate: daysAgo(45).toISOString(),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(45),
    project: proj.landTrust,
    client: client.rooted,
    owner: team.jl,
    accountManager: team.mm,
    assignedDeveloper: team.jl,
  },
  {
    id: 14,
    title: "Stewardship agreement templates",
    description: "Pre-built agreement templates with e-signature integration",
    status: "in-progress",
    priority: "medium",
    projectId: 4,
    clientId: 4,
    ownerId: "ar-3",
    accountManagerId: "mm-1",
    assignedDeveloperId: "ar-3",
    dueDate: daysAgo(-10).toISOString(),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
    project: proj.landTrust,
    client: client.rooted,
    owner: team.ar,
    accountManager: team.mm,
    assignedDeveloper: team.ar,
  },
  {
    id: 15,
    title: "Community voting module",
    description: "Anonymous ballot system for land trust governance decisions",
    status: "todo",
    priority: "high",
    projectId: 4,
    clientId: 4,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "tc-4",
    dueDate: daysAgo(-30).toISOString(),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    project: proj.landTrust,
    client: client.rooted,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.tc,
  },

  // --- Project 5: Carbon Credit (completed, 20/20 done) ---
  {
    id: 16,
    title: "Verification pipeline architecture",
    description:
      "Design automated credit verification workflow with auditor API",
    status: "done",
    priority: "high",
    projectId: 5,
    clientId: 5,
    ownerId: "mm-1",
    accountManagerId: "mm-1",
    assignedDeveloperId: "mm-1",
    dueDate: daysAgo(90).toISOString(),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(90),
    project: proj.carbon,
    client: client.verdant,
    owner: team.mm,
    accountManager: team.mm,
    assignedDeveloper: team.mm,
  },
  {
    id: 17,
    title: "Third-party auditor integration",
    description:
      "OAuth + webhook integration with Verra and Gold Standard registries",
    status: "done",
    priority: "high",
    projectId: 5,
    clientId: 5,
    ownerId: "tc-4",
    accountManagerId: "mm-1",
    assignedDeveloperId: "tc-4",
    dueDate: daysAgo(75).toISOString(),
    createdAt: daysAgo(130),
    updatedAt: daysAgo(75),
    project: proj.carbon,
    client: client.verdant,
    owner: team.tc,
    accountManager: team.mm,
    assignedDeveloper: team.tc,
  },
  {
    id: 18,
    title: "Credit issuance dashboard",
    description:
      "Admin view for reviewing, approving, and issuing carbon credits",
    status: "done",
    priority: "medium",
    projectId: 5,
    clientId: 5,
    ownerId: "jl-2",
    accountManagerId: "mm-1",
    assignedDeveloperId: "jl-2",
    dueDate: daysAgo(60).toISOString(),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(60),
    project: proj.carbon,
    client: client.verdant,
    owner: team.jl,
    accountManager: team.mm,
    assignedDeveloper: team.jl,
  },
];

// ---------------------------------------------------------------------------
// Contacts (for ContactKanban CRM demo)
// ---------------------------------------------------------------------------
export const SAMPLE_CONTACTS: ContactRow[] = [
  // Leads
  {
    id: "c-1",
    email: "elena@bioregionlabs.com",
    name: "Elena Vasquez",
    phone: "+1-512-555-0101",
    company: "Bioregion Labs",
    status: "lead",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["regenerative", "land-tech"],
    notes: "Interested in soil monitoring platform",
    lastContactAt: daysAgo(2),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-2",
    email: "james@greeninfra.org",
    name: "James Okafor",
    phone: null,
    company: "Green Infrastructure Alliance",
    status: "lead",
    source: "referral",
    referredBy: null,
    referredByExternal: "Conference contact",
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["urban", "community"],
    notes: "Met at regenerative cities summit",
    lastContactAt: daysAgo(5),
    submissionSources: ["manual"],
    portalClient: null,
  },
  {
    id: "c-3",
    email: "maria@seedcoop.org",
    name: "Maria Chen",
    phone: "+1-503-555-0199",
    company: "Seed Cooperative",
    status: "lead",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["agriculture", "cooperative"],
    notes: "Needs member management portal",
    lastContactAt: daysAgo(1),
    submissionSources: ["website"],
    portalClient: null,
  },
  // Prospects
  {
    id: "c-4",
    email: "david@terranova.co",
    name: "David Morales",
    phone: "+1-737-555-0142",
    company: "Terra Nova Collective",
    status: "prospect",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["land-tech", "carbon"],
    notes: "Proposal sent for canopy tracker",
    lastContactAt: daysAgo(3),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-5",
    email: "sarah@rootedcommons.org",
    name: "Sarah Whitfield",
    phone: "+1-512-555-0188",
    company: "Rooted Commons",
    status: "prospect",
    source: "referral",
    referredBy: null,
    referredByExternal: "David Morales",
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["community", "land-trust"],
    notes: "Scoping land trust portal features",
    lastContactAt: daysAgo(4),
    submissionSources: ["manual"],
    portalClient: null,
  },
  {
    id: "c-6",
    email: "kai@perennialag.net",
    name: "Kai Nakamura",
    phone: null,
    company: "Perennial Agriculture Network",
    status: "prospect",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["agriculture", "regenerative"],
    notes: "Interested in farm planning tool",
    lastContactAt: daysAgo(7),
    submissionSources: ["website"],
    portalClient: null,
  },
  // Clients
  {
    id: "c-7",
    email: "ana@livingsystems.co",
    name: "Ana Rivera",
    phone: "+1-512-555-0155",
    company: "Living Systems Co",
    status: "client",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["water", "land-tech"],
    notes: "Active watershed dashboard project",
    lastContactAt: daysAgo(1),
    submissionSources: ["website"],
    portalClient: {
      id: 3,
      slug: "living-systems",
      name: "Living Systems Co",
      company: "Living Systems Co",
    },
  },
  {
    id: "c-8",
    email: "marcus@verdantex.com",
    name: "Marcus Thompson",
    phone: "+1-415-555-0177",
    company: "Verdant Exchange",
    status: "client",
    source: "referral",
    referredBy: null,
    referredByExternal: "Ana Rivera",
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["carbon", "verification"],
    notes: "Carbon credit system delivered",
    lastContactAt: daysAgo(10),
    submissionSources: ["manual"],
    portalClient: {
      id: 5,
      slug: "verdant-exchange",
      name: "Verdant Exchange",
      company: "Verdant Exchange",
    },
  },
  {
    id: "c-9",
    email: "priya@bioregionlabs.com",
    name: "Priya Sharma",
    phone: "+1-512-555-0133",
    company: "Bioregion Labs",
    status: "client",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: "mm-1",
    accountManagerName: "Matthew Miceli",
    connectorId: null,
    assignedDeveloperId: "mm-1",
    createdBy: null,
    tags: ["regenerative", "land-tech", "sensors"],
    notes: "Soil monitoring -- phase 2 starting",
    lastContactAt: daysAgo(2),
    submissionSources: ["website"],
    portalClient: {
      id: 1,
      slug: "bioregion-labs",
      name: "Bioregion Labs",
      company: "Bioregion Labs",
    },
  },
  // Inactive
  {
    id: "c-10",
    email: "tom@oldgrowth.org",
    name: "Tom Bradley",
    phone: null,
    company: "Old Growth Foundation",
    status: "inactive",
    source: "website",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["forestry"],
    notes: "Budget constraints -- revisit Q3",
    lastContactAt: daysAgo(60),
    submissionSources: ["website"],
    portalClient: null,
  },
  {
    id: "c-11",
    email: "lisa@ecocraft.io",
    name: "Lisa Park",
    phone: "+1-206-555-0166",
    company: "EcoCraft Studios",
    status: "inactive",
    source: "manual",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["design"],
    notes: "Went with in-house solution",
    lastContactAt: daysAgo(45),
    submissionSources: ["manual"],
    portalClient: null,
  },
  // Churned
  {
    id: "c-12",
    email: "ryan@clearwater.co",
    name: "Ryan Foster",
    phone: null,
    company: "Clearwater Analytics",
    status: "churned",
    source: "referral",
    referredBy: null,
    referredByExternal: null,
    accountManagerId: null,
    accountManagerName: null,
    connectorId: null,
    assignedDeveloperId: null,
    createdBy: null,
    tags: ["analytics"],
    notes: "Scope mismatch -- too enterprise-focused",
    lastContactAt: daysAgo(90),
    submissionSources: ["manual"],
    portalClient: null,
  },
];
